sudo: false
language: python
python:
- '2.7'
- '3.6'
install:
- pip install -r requirements.txt
script:
- pylint postgresql setup.py
deploy:
  provider: pypi
  user: leonsp@ca.ibm.com
  password:
    secure: mWgHM208pAyeKq4q8e20wL4K6re+ICrCtKNz4kdDfuzBqoTtSaOxATeEX8AtSpW6ijBtUIZNii7l0tNpOW0wou9y61x5TxJDvpGniHbcmniSAy+IcfaLLCUgBj+RfgQHcjfwYKtM3Yprx3GO2G9DmU/IsU8ArJMLVExTysvh6lL0wnD0qGqyUAMYBKKyWpt0OriraCqFXa6WUMW27MSLbJOgVUlkm1T/mBSEhOFj3uDcp//cqAKtMikYwrR2SHVw2LHGIQq3o4gdzMJDKu59BA0KYYKo+okLRA2KKVTH5SoSbqw9MTJgu4qqQk6+rsEsx/us9Ttfz6kz5rfwtqwB1N+xr4HEMNCb+FmCs54Vcju9lA3+B2oLeZ8X5Eztr9jLfGCIa4nEUSxIVVDWYmMxarrNJLPyU8E9QrbgNIMtK1XGACnD+I+Zgco9WiBCGassYIWmq9+9r4zqPkDx9yZWyrQDrmml0OPQkDHCUZdREKH5E6BsfvepVjtcxhDEClz+Scla2a/N7BAuljXvGmjJPmqN2wMRr4D7WwOJcZTwhZLNxPfoYs8IO/Ey+G/s203zRd15jFkziT8SE2IiOHALgXDGeeWI1ehWQtni0gRUtF7hj/y+b0dud9OkAFQTcrTkZeFj8jIT32PjqR01ijTiiS7zUxsfpkfkoOj5eBY8Z2I=
  server: https://na.artifactory.swg-devops.com/artifactory/api/pypi/apset-pypi-local
  on:
    python: '2.7'
    tags: true
notifications:
  slack:
    secure: QTWVceIzxfMSiPquhjoHUXH2C97nHql2fzfeTMS0ntgA6aGEpSrErGbEw6Kc4m3ZY2P4LGfnc/cFoH9O/vCbnfOQH0MCEQM3DdgEgQg2hLpdzOb4KF2jnTyZ21YMMIVghteE+sEmrNNTXHsYgQQkT/eqWdg4ykJWIsaqHXk5mZyiD+b/T0im8vxE+7SwudQMmKVOPV8JfDPH0satvUF5K5V20bKhnwqMFmRwFOADzRiS5aOV1w5s/RO2E371ejLEI+sE1CBwG7EAsSQXh8tytTS54D5hyJZoUHRpirAEQjN9spYAvSMDIxAL1+B5fEwOvmKqcZ6Zc9oPq2me31djGnhAYWP+jgS5ki6d6aIn0plobSG2XOmQAzY6JGDPhN69X5kbi8FPBDpvuZq5iWIeEiKAw7RSQM5xY6k7Uc58dA/0+kqF9mYovhfXduVdq0xB4FYEF83g63FUmv4TKSzDoM/4WTGZ3t56diVUIdt138uQMD0a3hqHmy6s386bUkqwdjtapzPDAcpPHiojoLBdCi8jHMLGIlTFJCQ5ctQv9kgT2Ym1Veac76QpbbmlCvevPv9PHUqwjE8n0spjx+Yq2Kk4QsLOtqK9TKYDL0aKt9ajbqvEt+I9+IvofQQ3amw32QYAt5cjed1f5l2yzIrzlwSezefsm1aWkYe/8UKBgCw=
