language: python
python: '3.6'
cache:
  pip: true
install:
- pip install .
script:
- echo "no tests implemented"
deploy:
  - provider: pypi
    user: __token__
    password:
      secure: k2GTpgaigzo6QaaO2JFWHcp+OnC3gfkQSyMNrvxgpd+FKhimzVdt201W9Z/C4wM2p6lxGNwhd1K8as0kSBPPAAVIbe+eZigi0L4A82v1NjzH4zzBuOVLbwGewCDsz+14vvb6ZlkzMEQrxjPoMcfb6svFPIKu2x5edH5SOiOzFeB4AxrpsBNAEaMm0CPshEd/QenMg1h3t6T5otSw/6o5Z9brBJspqF/mO0zlvlFn8UcsncVgMYv7NX87n/FC0EHomM1LZx8n8+aXOTf9YBg7J/TSMshUCbeBdmGEuNDL2sPauhHH/y5pnMoXqQ0hsN6xJkD9QQEEMphJ5YFLGzvqCaN8fnu2Azft8yqqqTmrKwaYUBwnhGUyWUGWCmDLi2YPz/Sw6ayb4gjJBkdJlZm13TcG7kxhCdUlnItIxl/Ak1m8UhAxtsa+LWfm8+j237Vj337oYxKh6ZFd+sAf5YxE75+3QoNioEOe3hZ/+yh+dcVVerxvMDxgVbzhzQiKRyfsu7bVbRLbrMpbqywFsMe3iftdbS79/3oausoJXU2/F8KUcLPoOuIAnpNQRmu6LZ7LIsNUkFeH/c4KgZqzTM5no/aOUPAncuPfcfoIhaSZiBafxVY+F3WTNwJO7F1vnmc3mGs15PuucbiIhDHv9ejXRa0yC5QVasBuMcWcAk+96IY=
    on:
      tags: true
      repo: IBM/backwork-backup-postgresql
