language: python
python: '3.6'
cache:
  pip: true
install:
- pip install .
script:
- echo "no tests implemented"
deploy:
  - provider: pypi
    user: __token__
    password:
      secure: dMeSvZ5R4cxx2wqgReMcjMDoi7UoDRjPPW1nYfdFhgRZqyPQz8y7w8pmDAhLwhYc5tX37Z4Q5jQrSXRaB24FJn5d6RohPcblRihyCY5sutYOEmS53QeZAl//TLc8RJ0o4q7bPuOK0mdc2GONN8ihtXAM3uRFLZKCAsPViXLcGPqe18L/gxQRNx3IRwUxUKYouA6bFfK7lIv2DwpvAuqSq030NFRWRlr5kkaYVNEzWYIiidnqR5HgUpC6REmLbo1pl0nGbO1IbWjMD7Ogo7knYrGY9j7cJjhoWfDEwfhRWvE6DlT3ohS2ZljZ6FYExirUzAcRo9NrnW/3a7BK9m/fMKQuFv4zVzc2+16vmRDqpxxK9FU6gyODROJKQHdrTL0WJySVq6C78Frt2drRfJQKN9SjKa2K9d8cV70PCI2jJ5TfkTxn8FO+qiueuFD2HK2YqhwlFKAspWo4scLvIoFsCNbbQAmDyzmEzSlnVTjcey7+pmM667ydPWhvCkDLyvstHrLovSXeV9tNc59tX22BquhcNhJvYODpDVIlbbRTnVlGWuOKcUXLqzFkFSi2vAciEPIQkIZ//sAmg3+G+KptJa/h+oGy+eNmB2U655SUCJ254jKvhx6EYOpY+8DB12lexP6U2l0EMhw7+dwaNKPOi8oXi5ZH44HnAN8Tb4twHno=
    on:
      tags: true
      repo: IBM/backwork-backup-postgresql
